### ISSUE TITLE
Neo4j Cypher step should use writeTransaction instead of run

### ISSUE THREAD

**Issue by mattcasters** [knowbi/knowbi-pentaho-pdi-neo4j-output#125]
This would better support clustered scenarios

**Comment by mattcasters** [comment]
```
2019/04/16 22:59:43 - Table input.0 - linenr 9000000
org.neo4j.driver.v1.exceptions.SessionExpiredException: Server at SERVER-A no longer accepts writes
    at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:122)
    at org.neo4j.driver.internal.InternalStatementResult.blockingGet(InternalStatementResult.java:134)
    at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:64)
    at bi.know.kettle.neo4j.steps.cypher.Cypher.writeResultRows(Cypher.java:321)
    at bi.know.kettle.neo4j.steps.cypher.Cypher.processRow(Cypher.java:243)
    at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
```

**Comment by mattcasters** [comment]
We'll need an option to allow the user to flag the Cypher as read-only.  In that case we would use ```session.readTransaction()```.  If not we'd use ```session.writeTranaction()```

**Comment by mattcasters** [comment]
run() will be only kept if the batch size is <= 1
