### ISSUE TITLE
NPE in Neo4j perspective

### ISSUE THREAD

**Issue by mattcasters** [knowbi/knowbi-pentaho-pdi-neo4j-output#140]
At startup we see this in the log:

```2019/09/20 14:40:25 - General - ERROR (version 8.2.0.7-719, build 8.2.0.7-719 from 2019-06-27 12.22.51 by kettle) : Error initializing perspective
2019/09/20 14:40:25 - General - ERROR (version 8.2.0.7-719, build 8.2.0.7-719 from 2019-06-27 12.22.51 by kettle) : java.lang.NullPointerException
2019/09/20 14:40:25 - General - 	at org.kettle.beam.perspective.BeamPerspective.addAdminTab(BeamPerspective.java:109)
2019/09/20 14:40:25 - General - 	at org.kettle.beam.perspective.BeamPerspective.<init>(BeamPerspective.java:84)
2019/09/20 14:40:25 - General - 	at org.kettle.beam.perspective.BeamSpoonPlugin.<init>(BeamSpoonPlugin.java:40)
2019/09/20 14:40:25 - General - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2019/09/20 14:40:25 - General - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2019/09/20 14:40:25 - General - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2019/09/20 14:40:25 - General - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2019/09/20 14:40:25 - General - 	at java.lang.Class.newInstance(Class.java:442)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:491)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:340)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.ui.spoon.SpoonPluginManager.pluginAdded(SpoonPluginManager.java:65)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.ui.spoon.SpoonPluginManager.<init>(SpoonPluginManager.java:173)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.ui.spoon.SpoonPluginManager.<clinit>(SpoonPluginManager.java:58)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.ui.spoon.Spoon.init(Spoon.java:890)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.ui.spoon.Spoon.createContents(Spoon.java:9142)
2019/09/20 14:40:25 - General - 	at org.eclipse.jface.window.Window.create(Window.java:426)
2019/09/20 14:40:25 - General - 	at org.eclipse.jface.window.Window.open(Window.java:785)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9173)
2019/09/20 14:40:25 - General - 	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:707)
2019/09/20 14:40:25 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019/09/20 14:40:25 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019/09/20 14:40:25 - General - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019/09/20 14:40:25 - General - 	at java.lang.reflect.Method.invoke(Method.java:498)
2019/09/20 14:40:25 - General - 	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
2019/09/20 14:40:26 - General - ERROR (version 8.2.0.7-719, build 8.2.0.7-719 from 2019-06-27 12.22.51 by kettle) : Error initializing perspective
2019/09/20 14:40:26 - General - ERROR (version 8.2.0.7-719, build 8.2.0.7-719 from 2019-06-27 12.22.51 by kettle) : java.lang.NullPointerException
2019/09/20 14:40:26 - General - 	at bi.know.kettle.neo4j.perspective.Neo4jPerspective.addAdminTab(Neo4jPerspective.java:131)
2019/09/20 14:40:26 - General - 	at bi.know.kettle.neo4j.perspective.Neo4jPerspective.<init>(Neo4jPerspective.java:110)
2019/09/20 14:40:26 - General - 	at bi.know.kettle.neo4j.perspective.Neo4jSpoonPlugin.<init>(Neo4jSpoonPlugin.java:40)
2019/09/20 14:40:26 - General - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2019/09/20 14:40:26 - General - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2019/09/20 14:40:26 - General - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2019/09/20 14:40:26 - General - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2019/09/20 14:40:26 - General - 	at java.lang.Class.newInstance(Class.java:442)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:491)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:340)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.ui.spoon.SpoonPluginManager.pluginAdded(SpoonPluginManager.java:65)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.ui.spoon.SpoonPluginManager.<init>(SpoonPluginManager.java:173)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.ui.spoon.SpoonPluginManager.<clinit>(SpoonPluginManager.java:58)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.ui.spoon.Spoon.init(Spoon.java:890)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.ui.spoon.Spoon.createContents(Spoon.java:9142)
2019/09/20 14:40:26 - General - 	at org.eclipse.jface.window.Window.create(Window.java:426)
2019/09/20 14:40:26 - General - 	at org.eclipse.jface.window.Window.open(Window.java:785)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9173)
2019/09/20 14:40:26 - General - 	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:707)
2019/09/20 14:40:26 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019/09/20 14:40:26 - General - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019/09/20 14:40:26 - General - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019/09/20 14:40:26 - General - 	at java.lang.reflect.Method.invoke(Method.java:498)
2019/09/20 14:40:26 - General - 	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
```

**Comment by mattcasters** [comment]
Let's disable the perspective for now.  Not sure it's used anyway.
