### ISSUE TITLE
Neo4j 5.x betas throw Class Not Found for Neo4j Graph Output --> Export Model

### ISSUE THREAD

**Issue by davidlrosenblum** [knowbi/knowbi-pentaho-pdi-neo4j-output#170]
Clicking Export graph to JSON button throws error below.

![Screen Shot 2020-02-20 at 4 14 17 PM](https://user-images.githubusercontent.com/21196824/74979271-4e600100-53fc-11ea-853e-30dba99d28ba.png)

> Unable to open dialog for this step
java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
	at org.neo4j.kettle.model.GraphModel.getJSONString(GraphModel.java:216)
	at bi.know.kettle.neo4j.model.GraphModelDialog.getModelJson(GraphModelDialog.java:1748)
	at bi.know.kettle.neo4j.model.GraphModelDialog.exportGraphToFile(GraphModelDialog.java:1738)
	at bi.know.kettle.neo4j.model.GraphModelDialog.lambda$addModelTab$5(GraphModelDialog.java:464)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at bi.know.kettle.neo4j.model.GraphModelDialog.open(GraphModelDialog.java:200)
	at bi.know.kettle.neo4j.model.GraphModelUtils.editModel(GraphModelUtils.java:75)
	at bi.know.kettle.neo4j.steps.graph.GraphOutputDialog.editModel(GraphOutputDialog.java:618)
	at ...

**Comment by mattcasters** [comment]
Ah, thanks!  The lib is ```json-simple-1.1.jar``.  You can steal the one from the v4 plugins

**Comment by davidlrosenblum** [comment]
Thanks!  That worked.
Will that be in the final build?

**Comment by davidlrosenblum** [comment]
oops - green button, not red one!

**Comment by mattcasters** [comment]
Yes, this will be in the final build which I'll be running through the integration tests to release in the next couple of days.
