### ISSUE TITLE
java.lang.NullPointerException in components of NEO4J using the repository

### ISSUE THREAD

**Issue by rbortolini** [knowbi/knowbi-pentaho-pdi-neo4j-output#173]
I'm using the new plugin (Neo4JOutput-5.0.0) and it's returning an error in the component (Neo4J Output)
of the PDI when it is saved in the Repository.

PDI version used for the test: (8.2.0.0), (8.3.0.0) and (9.0.0.0)
Neo4JOutput version used for the test: (4.0.0), (4.0.1), (4.1.1) and (5.0.0)

java.lang.NullPointerException
	at bi.know.kettle.neo4j.steps.output.Neo4JOutputDialog.getData(Neo4JOutputDialog.java:782)
	at bi.know.kettle.neo4j.steps.output.Neo4JOutputDialog.open(Neo4JOutputDialog.java:713)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:120)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8833)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3287)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:785)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1385)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7968)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9350)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:711)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

	
The version that is working when I use the repository is Neo4JOutput (3.13.3).
If I use the transformation saved to file it works without a problem.

**Comment by mattcasters** [comment]
Thanks for the bug report. What kind of repository are you using? (please don't by the way. do yourself a favor :-))

**Comment by mattcasters** [comment]
See also: https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/issues/138

**Comment by rbortolini** [comment]
I'm using the SQLServer repository that was created in version 5.4 of the PDI.
I created a new repository in SQLServer in version 9.0 of the PDI made an export / import
metadata for this new repository and also gave the same error.

Do you think it is better to work on file than in the repository?

Thanks for your help.

**Comment by rbortolini** [comment]
I had already looked at post # 138 so I understand he is having trouble generating the connection.
In my execution the connection is working, when I run it has the error or after saving if I open the transformation again I have the error.
![image](https://user-images.githubusercontent.com/55597898/75931235-3ef8a300-5e53-11ea-876b-f9688fa48dd4.png)

**Comment by mattcasters** [comment]
#138 refers the "Enterprise Repository".  It was a bug report from someone at Hitachi Vantara.
You're using a database repository which behaves differently wrt to metastore objects.  I haven't used this sort of repository since git was invented :-)
