### ISSUE TITLE
ClassCastException when importing a Cypher Workbench model json

### ISSUE THREAD

**Issue by voutilad** [knowbi/knowbi-pentaho-pdi-neo4j-output#182]
When using "Import Cypher Workbench model" and supplying my [data model](https://gist.github.com/voutilad/eb0e7bac32ed5c540f051d7979b590e9), I'm getting the following error:

```
org.pentaho.di.core.exception.KettleException: 
Error parsing Cypher Workbench model
java.lang.Double cannot be cast to java.lang.Long

	at org.neo4j.kettle.model.cw.CypherWorkbenchImporter.importFromCwJson(CypherWorkbenchImporter.java:89)
	at bi.know.kettle.neo4j.model.GraphModelDialog.importGraphFromCypherWorkbench(GraphModelDialog.java:1796)
	at bi.know.kettle.neo4j.model.GraphModelDialog.lambda$addModelTab$6(GraphModelDialog.java:486)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at bi.know.kettle.neo4j.model.GraphModelDialog.open(GraphModelDialog.java:201)
	at bi.know.kettle.neo4j.model.GraphModelUtils.newModel(GraphModelUtils.java:32)
	at bi.know.kettle.neo4j.perspective.Neo4jHelper.createModel(Neo4jHelper.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:545)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:490)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:402)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1381)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7816)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9178)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:707)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
	at org.neo4j.kettle.model.cw.CypherWorkbenchImporter.importFromCwJson(CypherWorkbenchImporter.java:54)
	... 35 more

```

**Comment by mattcasters** [comment]
See: https://github.com/mattcasters/kettle-neo4j-core/issues/10
