### ISSUE TITLE
neo4j output get error

### ISSUE THREAD

**Issue by limsai-ai** [knowbi/knowbi-pentaho-pdi-neo4j-output#201]
the target database version is 4.2.3
the setting of neo4j output comment is refer to [https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/wiki/Neo4j-Output]
2021/02/23 16:12:27 - Neo4J Output.0 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Unexpected error
2021/02/23 16:12:27 - Neo4J Output.0 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : java.lang.NullPointerException
2021/02/23 16:12:27 - Neo4J Output.0 - 	at bi.know.kettle.neo4j.steps.output.Neo4JOutput.processRow(Neo4JOutput.java:115)
2021/02/23 16:12:27 - Neo4J Output.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/02/23 16:12:27 - Neo4J Output.0 - 	at java.lang.Thread.run(Thread.java:748)
2021/02/23 16:12:27 - Neo4J Output.0 - child index = 3, logging object : org.pentaho.di.core.logging.LoggingObject@162f221 parent=49319948-a478-49ad-b772-1d8ed8848f29

**Comment by mattcasters** [comment]
At the very least update to the latest version of this plugin, version 5.0.7 right now.

**Comment by limsai-ai** [comment]
The version I use is 5.0.7  
the first step  I use table input comment to get data ,the sql is 
  **select  swjg_dm nsrsbh,swjg_mc nsrmc,name  from nsrxx**
the second step  I use Add constants comment to set the lable name
the last step just like I said above

**Comment by mattcasters** [comment]
Feel free to let us know what options you used, specifically for the node label: static or dynamic label.
I'd be happy to fix the issue once I have a reproduction path.

**Comment by limsai-ai** [comment]
I used static label，Same as the configuration on the document [https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/wiki/Neo4j-Output](url)
the add constants  step contail one constant which named 'label' and value is 'NSR'
the from node options:
From Label Filed   From Label Filed Values  
label                     null

From Property Field      Property  Name      Property type     Primary key?
nsrsbh                          nsrsbh                      String                  N 
nsrsmc                         nsrsmc                      String                  N 
name                           name                      String                  N 

the other options  is default 
thanks

**Comment by mattcasters** [comment]
Thanks!  So that would actually be a dynamic label since it can change per row.
