### ISSUE TITLE
Neo4j Graph Output not working in Pentaho Server 8.2

### ISSUE THREAD

**Issue by EduardoVink** [knowbi/knowbi-pentaho-pdi-neo4j-output#204]
Using:

- Pentaho Server 8.2.0.0-342
- PDI 8.2.0.7.719
- Neo4j 4.3.2
- Neo4JOutput plugin 5.0.8 
- Windows 10 Pro 21H1

We are testing the steps in the plugin for a project and encountered that Graph Output step doesn't work in Pentaho Server. Locally, executing the same testing transformation (a Text File Input connected to a Neo4j Graph Output step) works just fine. The model takes all the users from a CSV and creates nodes with the _User_ label, and the value in the column _user_id_ as its only property.

The path where we extracted the plugin is:
~\server\pentaho-server\pentaho-solutions\system\kettle\plugins

How can we execute this step inside Pentaho Server?

Here's the log of the fault execution:
```2021/08/09 15:24:18 - Spoon - Using legacy execution engine
2021/08/09 15:24:18 - Spoon - Transformation opened.
2021/08/09 15:24:18 - Spoon - Launching transformation [trn_Neo4j_02]...
2021/08/09 15:24:18 - Spoon - Started the transformation execution.
2021/08/09 15:24:18 - trn_Neo4j_02 - Dispatching started for transformation [trn_Neo4j_02]
2021/08/09 15:24:19 - Text file input.0 - Opening file: file:///D:/Documents/Neo4j/ecommerce_example_data/ecommerce_data/ecommerce_cypher_step.csv
2021/08/09 15:24:19 - Neo4j Graph Output.0 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Unexpected error
2021/08/09 15:24:19 - Neo4j Graph Output.0 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2021/08/09 15:24:19 - Neo4j Graph Output.0 - Unable to find target node 'user_id'
2021/08/09 15:24:19 - Neo4j Graph Output.0 - 
2021/08/09 15:24:19 - Neo4j Graph Output.0 - 	at bi.know.kettle.neo4j.steps.graph.GraphOutput.createNodePropertyIndexes(GraphOutput.java:309)
2021/08/09 15:24:19 - Neo4j Graph Output.0 - 	at bi.know.kettle.neo4j.steps.graph.GraphOutput.processRow(GraphOutput.java:244)
2021/08/09 15:24:19 - Neo4j Graph Output.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2021/08/09 15:24:19 - Neo4j Graph Output.0 - 	at java.lang.Thread.run(Thread.java:748)
2021/08/09 15:24:19 - Neo4j Graph Output.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)
2021/08/09 15:24:19 - Text file input.0 - Finished processing (I=51, O=0, R=0, W=49, U=1, E=0)
2021/08/09 15:24:19 - trn_Neo4j_02 - Transformation detected one or more steps with errors.
2021/08/09 15:24:19 - trn_Neo4j_02 - Transformation is killing the other steps!
2021/08/09 15:24:19 - trn_Neo4j_02 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Errors detected!
2021/08/09 15:24:19 - Spoon - The transformation has finished!!
2021/08/09 15:24:19 - trn_Neo4j_02 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Errors detected!
2021/08/09 15:24:19 - trn_Neo4j_02 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Errors detected!```

**Comment by mattcasters** [comment]
Ah, it's a bug in the serialization for the enterprise repository. I'll fix it this week for sure.

**Comment by EduardoVink** [comment]
Thank you, Matt!

**Comment by mattcasters** [comment]
Give this a try please:  https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/releases/tag/5.0.9
