### ISSUE TITLE
Error encoding to XML  

### ISSUE THREAD

**Issue by beexpectedone** [knowbi/knowbi-pentaho-pdi-neo4j-output#21]
when it is used in  my remote server   , there will be a error :Error encoding to XML
java.lang.NullPointerException
	at bi.know.kettle.neo4j.output.Neo4JOutputMeta.getXML(Neo4JOutputMeta.java:75)
	at org.pentaho.di.trans.step.StepMeta.getXML(StepMeta.java:221)
	at org.pentaho.di.trans.step.StepMeta.getXML(StepMeta.java:197)
	at org.pentaho.di.ui.spoon.Spoon.copySelected(Spoon.java:3472)
	at org.pentaho.di.ui.spoon.Spoon.copySteps(Spoon.java:1423)
	at org.pentaho.di.ui.spoon.Spoon.copy(Spoon.java:1451)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:545)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:490)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:402)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1339)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7939)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9214)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:653)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

**Comment by beexpectedone** [comment]
when  i  close the repository connection， the error  will  disappear

**Comment by mattcasters** [comment]
Which version were you using at the time?

**Comment by mattcasters** [comment]
Please feel free to re-open when you feel the need

**Comment by mattcasters** [comment]
That was true for the old 0.1 version. Recent versions can be used with repositories (even though we typically don't when we have git)
