### ISSUE TITLE
Neo4j Cypher - Unable to list Neo4j connections 

### ISSUE THREAD

**Issue by antonio-castellon** [knowbi/knowbi-pentaho-pdi-neo4j-output#36]
Dear Know.bi Team,

I just tried the transformation Neo4j Cypher and it throws an exception "Unable to list Neo4j connections" . it means that I cannot configure this module to be connected with Neo4j. I declared 2 connections on my project (One from Generic JDBC Driver and the other, using the Neo4j connection already declared into Connections list) and both are working well according to the test. But the Cypher module doesn't show the list of available connectors.

Also, I tried to create a connection from the New connection button inside of the Cypher module, but it throws this exception when I tried to save it.
```

java.lang.NullPointerException
	at org.pentaho.metastore.stores.delegate.DelegatingMetaStore.getElements(DelegatingMetaStore.java:275)
	at org.pentaho.metastore.stores.delegate.DelegatingMetaStore.getElementByName(DelegatingMetaStore.java:314)
	at org.pentaho.metastore.persist.MetaStoreFactory.loadElement(MetaStoreFactory.java:77)
	at bi.know.kettle.neo4j.shared.NeoConnectionUtils.newConnection(NeoConnectionUtils.java:38)
	at bi.know.kettle.neo4j.steps.cypher.CypherDialog.newConnection(CypherDialog.java:562)
	at bi.know.kettle.neo4j.steps.cypher.CypherDialog$4.widgetSelected(CypherDialog.java:423)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at bi.know.kettle.neo4j.steps.cypher.CypherDialog.open(CypherDialog.java:447)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:120)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8949)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3291)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:785)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1375)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:8104)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9466)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:701)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
```

Any idea how to fixed?
Thanks in advance,
Antonio

**Comment by antonio-castellon** [comment]
I just removed all from the local repository folder and it works again.
